### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by SpicyCupcakes** [TheOnlyLordVirus/Predator-BlackOps3-RTM-Tool-PS3#1]
I installed the one for PC but it does not do anything.  It does not let me connect to my game, even after putting in the IP my IP for the pc running the game.

**Comment by TheOnlyLordVirus** [comment]
This is a common issue. Your PS3 must be running a DEX firmware and your qa flag must be toggled; furthermore your debug settings in your qa flag have to be set to:
Release Check Mode> Development Mode
Boot Mode> System Software mode

**Comment by TheOnlyLordVirus** [comment]
Let me know if this fixes your issue!
You need to change these settings otherwise the Predator RTM tool will not have access to regions in memory where most of the modifications take place using this tool. 

What version of CCAPI are you using?

**Comment by SpicyCupcakes** [comment]
PS3, LMFAO.  I though this was available for PC too.  Sorry for the
misunderstanding.  Google is always misleading me this way.  I could have
sworn that I specified PC.

**Comment by TheOnlyLordVirus** [comment]
Ohh nope, sorry friend.
